# Generated by Django 5.0.3 on 2024-03-18 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Sarlavha')),
                ('photo', models.ImageField(default='blog/1.jpg', upload_to='blog/')),
                ('short_content', models.TextField(verbose_name='Qisqa ma`lumot')),
                ('content', models.TextField(verbose_name='Ma`lumot')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 17, 1, 52, 922588, tzinfo=datetime.timezone.utc), verbose_name='Nashir Sanasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashir etilgan')], default='draft', max_length=250, verbose_name='Holati')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
