# Generated by Django 5.0.3 on 2024-03-18 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 17, 5, 39, 453630, tzinfo=datetime.timezone.utc), verbose_name='Nashir Sanasi'),
        ),
    ]
