# Generated by Django 5.0.3 on 2024-04-17 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_alter_blog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 14, 53, 18, 899130, tzinfo=datetime.timezone.utc), verbose_name='Nashir Sanasi'),
        ),
    ]
